# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  demands: 
    Server_Unity_Build

steps:
#cleanup for unity build
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**/*'

#get the previously secured library (if any) for performance reasons
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\VR Prototype\Library'
    Contents: '**/*'
- task: CmdLine@2
  inputs:
    script: 'if EXIST "$(Build.Repository.LocalPath)\LibraryBackup" robocopy "$(Build.Repository.LocalPath)\LibraryBackup" "$(Build.Repository.LocalPath)\VR Prototype\Library" /MIR'

- task: UnityActivateLicenseTask@1
  inputs:
    username: '$(Unity.Username)'
    password: '$(Unity.Password)'
    serial: '$(Unity.Serial)'
    unityProjectPath: 'test'

#unity PC build
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Win64'
    unityProjectPath: 'test'
    outputPath: '$(Build.BinariesDirectory)\Build'
    outputFileName: 'VR Prototype'

#Delete DoNotShip folders
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)\Build'
    Contents: '?(*_DoNotShip)'

#Backup the library for next build
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\VR Prototype\Library'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)\LibraryBackup'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)\Build'
    Contents: '**\*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Build'

#upload artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Build'
    ArtifactName: 'drop'
    publishLocation: 'Container'